aws_region         = "us-east-1"
project_name       = "meridian-chatbot"
backend_image_tag  = "latest"
frontend_image_tag = "latest"
mcp_server_url     = "https://order-mcp-74afyau24q-uc.a.run.app/mcp"
groq_api_key       = "replace_me"
